# Billboard Data
This notebook uses the [billboard.py](https://github.com/guoguo12/billboard-charts) library.

In [51]:
from datetime import date
import billboard
import pandas as pd

today = date.today().strftime("%d/%m/%Y")
print('Ran on: ' + today)

Ran on: 21/11/2022

In [ ]:
hotOneHundred = billboard.ChartData('hot-100')

print(hotOneHundred)

In [37]:
songs = []
for chartEntry in hotOneHundred:
    song = {
        'title': chartEntry.title, 
        'artist': chartEntry.artist, 
        'peakPos': chartEntry.peakPos, 
        'lastPos': chartEntry.lastPos, 
        'weeks': chartEntry.weeks, 
        'rank': chartEntry.rank, 
        'isNew': chartEntry.isNew
    }
    songs.append(song)
df = pd.DataFrame(songs)
df

,title,artist,peakPos,lastPos,weeks,rank,isNew
0,Anti-Hero,Taylor Swift,1,1,3,1,False
1,Rich Flex,Drake & 21 Savage,2,0,1,2,True
2,Major Distribution,Drake & 21 Savage,3,0,1,3,True
3,On BS,Drake & 21 Savage,4,0,1,4,True
4,Spin Bout U,Drake & 21 Savage,5,0,1,5,True
...,...,...,...,...,...,...,...
95,La Bachata,Manuel Turizo,67,90,12,96,False
96,2 Be Loved (Am I Ready),Lizzo,55,80,13,97,False
97,High Infidelity,Taylor Swift,33,79,3,98,False
98,Gotta Move On,Diddy & Bryson Tiller,79,91,6,99,False
99,Staying Alive,DJ Khaled Featuring Drake & Lil Baby,5,81,14,100,False

## Sort by Weeks on the Hot 100

In [48]:
df.sort_values(by='weeks', ascending=False)

,title,artist,peakPos,lastPos,weeks,rank,isNew
36,Wasted On You,Morgan Wallen,9,22,52,37,False
16,As It Was,Harry Styles,1,5,32,17,False
47,About Damn Time,Lizzo,1,33,30,48,False
25,Something In The Orange,Zach Bryan,12,29,29,26,False
58,Fall In Love,Bailey Zimmerman,29,50,28,59,False
...,...,...,...,...,...,...,...
14,Middle Of The Ocean,Drake,15,0,1,15,True
15,Jumbotron Shit Poppin,Drake,16,0,1,16,True
17,More Mâ€™s,Drake & 21 Savage,18,0,1,18,True
18,I Guess It's Fuck Me,Drake,19,0,1,19,True
13,Treacherous Twins,Drake & 21 Savage,14,0,1,14,True